apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprival-app
  namespace: default
  labels:
    app: sprival-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprival-app
  template:
    metadata:
      labels:
        app: sprival-app
    spec:
      containers:
        - name: sprival-app
          image: sprival/app:0.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8383
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

