apiVersion: v1
kind: Service
metadata:
  name: sprival-app
  namespace: default
  labels:
    app: sprival-app
spec:
  type: ClusterIP
  selector:
    app: sprival-app
  ports:
    - name: http
      port: 8383
      targetPort: 8383

