version: '3'

networks:
  frontend:
    driver: bridge

volumes:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_cache:


services:
  ### gitlab ###################################################
  # docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        nginx['client_max_body_size'] = '250m'
        gitlab_rails['artifacts_max_size'] = 250
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - frontend
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    privileged: true
    volumes:
      - './gitlab-runner/config:/etc/gitlab-runner' # 持久化配置
      - gitlab_runner_cache:/cache # 缓存
      - '/var/run/docker.sock:/var/run/docker.sock' # 访问宿主机 Docker
    networks:
      - frontend # 同一网络
    depends_on:
      - gitlab
