networks:
  frontend:
    driver: bridge

volumes:
  grafana:
  prometheus:

services:
  ### Grafana ###################################################
  grafana:
    build:
      context: ./grafana
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=workdock
    ports:
      - "3000:3000"
    networks:
      - frontend
    links:
      - prometheus

  ### Prometheus ###################################################
  prometheus:
    build:
      context: ./prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus/prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - frontend
